# Generated by Django 6.0 on 2026-01-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('mentor', 'mentor'), ('student', 'student')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
