# Generated by Django 6.0 on 2026-01-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('mentor', 'mentor'), ('student', 'student')], default='student', max_length=20),
        ),
    ]
