# Generated by Django 6.0 on 2026-01-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_year', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('fantasy', 'Фэнтези'), ('fantastic', 'Фантастика'), ('detective', 'Детектив'), ('novel', 'Роман'), ('fiction', 'Художественная литература'), ('science', 'Научная'), ('history', 'История'), ('fairy_tale', 'Сказки'), ('other', 'Другие')], max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
